# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회 및 변경

## 배열 인덱싱

- 팬시(fancy) 인덱싱
    - 여러개의 원소를 한번에 조회할 경우 리스트에 담아 전달
    - 다차원 배열의 경우 각 축별로 list로 지정
    - arr[[1, 2, 3, 4, 5]]
        - 1차원 배열(vector): 1, 2, 3, 4, 5 번 index의 원소들 한번에 조회
    - arr[[0, 3], [1, 4]]
        - [0, 3] -1분축 index list, [1, 4] -2번축 index list
        - 2차원 배열(matrix) : [0, 1], [3, 4]의 원소들 조회 

In [3]:
import numpy as np
a = np.arange(30)
print(a.shape)

(30,)


In [4]:
# 여러 index들의 값 조회 => fancy indexing => index들을 리스트로 묶어서 전달
a[[1, 3, 2, 7]]

array([1, 3, 2, 7])

In [5]:
# 조회
print(a[1])
# 변경
a[1] = 10000
a

1


array([    0, 10000,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29])

In [6]:
# 일괄변경
a[[2, 4, 6]] = 5000
a

array([    0, 10000,  5000,     3,  5000,     5,  5000,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29])

In [7]:
a[[8, 9, 10]] = 8000, 9000, 10000
a

array([    0, 10000,  5000,     3,  5000,     5,  5000,     7,  8000,
        9000, 10000,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29])

In [8]:
a2 = np.arange(30).reshape(5, 6)
# (30, ) 1차원 배열을 (5, 6) 2차원 배열로 reshape
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
print(a2[0])
print(a2[0, 3])

[0 1 2 3 4 5]
3


In [10]:
a2[[0, 3, 1, 4], [2, 4, 3, 5]]
# [0, 2], [3, 4], [1, 3], [4, 5]


array([ 2, 22,  9, 29])

In [12]:
a3 = np.arange(12).reshape(2, 2, 3)
print(a3.shape)
a3

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
print(a3[0, 1, 1], a3[1, 1, 2])

4 11


## 슬라이싱

In [14]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
print(a[:5])
print(a[2:15:3])
print(a[20:-1])

[0 1 2 3 4]
[ 2  5  8 11 14]
[20 21 22 23 24 25 26 27 28]


In [16]:
a[:4] = 400
a

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [17]:
b = a[:4].copy()
print(b)
print(b[0])
b[0] = 5000
b

[400 400 400 400]
400


array([5000,  400,  400,  400])

In [18]:
a2 = np.arange(30).reshape(5, 6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [22]:
print(a2[[1, -1], 1:5])
print("="*20)
print(a2[1, 1:5])
print("="*20)
print(a2[:, [1, 4]])

[[ 7  8  9 10]
 [25 26 27 28]]
[ 7  8  9 10]
[[ 1  4]
 [ 7 10]
 [13 16]
 [19 22]
 [25 28]]


## boolean indexing

### 넘파이 비교 연산자
- 파이썬의 and, or, not은 사용할 수 없다
- & : and 연산
- | : or 연산
- ~ : not 연산
- 피연산자는 ()로 묶는다

In [23]:
np.random.seed(0)
a = np.random.randint(100, size = 20)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [24]:
# a에서 50이상인 값들만 조회
a[a>50]

array([64, 67, 67, 83, 87, 70, 88, 88, 58, 65, 87, 88])

In [25]:
# 30 < a < 60
a[(a > 30) & (a < 60)]

array([44, 47, 36, 58, 39, 46])

In [27]:
# 30 ~ 60 이 아닌 값
print(a[~((a > 30) & (a < 60))])
print(a[(a <= 30) | (a >= 60)])

[64 67 67  9 83 21 87 70 88 88 12 65 87 88]
[64 67 67  9 83 21 87 70 88 88 12 65 87 88]


In [28]:
a2 = np.random.randint(100, size = (7, 8))
a2

array([[81, 37, 25, 77, 72,  9, 20, 80],
       [69, 79, 47, 64, 82, 99, 88, 49],
       [29, 19, 19, 14, 39, 32, 65,  9],
       [57, 32, 31, 74, 23, 35, 75, 55],
       [28, 34,  0,  0, 36, 53,  5, 38],
       [17, 79,  4, 42, 58, 31,  1, 65],
       [41, 57, 35, 11, 46, 82, 91,  0]])

In [30]:
print((a2 > 50).shape)
print(a2[a2 > 50]) # 결과는 1차원으로 반환

(7, 8)
[81 77 72 80 69 79 64 82 99 88 65 57 74 75 55 53 79 58 65 57 82 91]


## np.where()
- True의 index 조회
    - np.where(boolean 배열) - True인 index를 반환
    - boolean연산과 같이 사용하여 베열내에 특정 조건을 만족하는 값들을 index(위치)를 조회할 때 사용
- True와 False를 다른 값으로 변환
    - np.where(boolean 배열, True를 대체할 값, False를 대체할 값)

In [31]:
r = np.where([True, False, True])
print(type(r), type(r[0]))
r

<class 'tuple'> <class 'numpy.ndarray'>


(array([0, 2], dtype=int64),)

In [32]:
r2 = np.where([True, False, True], '참', '거짓')
r2

array(['참', '거짓', '참'], dtype='<U2')

In [33]:
l = [
    [True, False, True],
    [False, False, True]
]
r3 = np.where(l)
r3

(array([0, 0, 1], dtype=int64), array([0, 2, 2], dtype=int64))

In [34]:
for a1, a2 in zip(r3[0], r3[1]):
    print(a1, a2, sep = ', ')

0, 0
0, 2
1, 2


In [35]:
np.random.seed(0)
a2 = np.random.randint(100, size = (5, 2, 3))
a2.shape

(5, 2, 3)

In [36]:
# 70이상인 값들 조회 => 조건이 True값들을 조회 => boolean indexing
a2[a2 >= 70]

array([83, 87, 70, 88, 88, 87, 88, 81, 77, 72, 80, 79])

In [37]:
# 70 이상인 값들의 위치 => 조건이 True 값들의 위치(index) => np.where()
axis1, axis2, axis3 = np.where(a2 >= 70)
print(axis1)
print(axis2)
print(axis3)

[1 1 1 1 2 2 3 3 3 4 4 4]
[0 1 1 1 0 1 0 0 1 0 1 1]
[0 0 1 2 0 2 1 2 2 0 0 2]


In [38]:
for i, j, k in zip(axis1, axis2, axis3):
    print(a2[i, j, k], end = ', ')

83, 87, 70, 88, 88, 87, 88, 81, 77, 72, 80, 79, 

## 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
    - 배열내에 특정 조건을 만족하는 값이 하나 이상 있는지 확인할 때 사용
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환
    - 배열내의 모든 원소가 특정 조건을 만족하는지 확인할 때 사용

In [39]:
print(np.any([True, False, False, False]))
print(np.any([False, False, False, False]))

True
False


In [40]:
print(np.any(a2 == 99))
print(np.any(a2 == 83))

False
True


In [41]:
print(np.all([True, True, False]))
print(np.all([True, True, True]))

False
True


In [42]:
print(np.all(a2>0))
print(np.all(a2>10))

True
False


## 배열의 형태(shape) 변경
### reshape()을 이용한 차원 변경
- numpy.reshape(a, newshape) 또는 ndarray.reshape(newshape)
    - a : 형태를 변경할 배열
    - newshaoe : 변경할 형태 설정
        - 원소 개수를 유지하는 shape으로만 변환 가능
        - 하나의 축의 size를 -1로 줄 수 있다
            - 전체 size / 다른 축의 size곱을 -1로 지정한 axis의 size로 지정
    - 원본을 바꾸지 않고 reshape한 새로운 배열을 반환

In [43]:
a = np.arange(20)
print(a.shape)
a

(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
r1 = np.reshape(a, (2, 10))
print(r1.shape)
r1

(2, 10)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
r2 = a.reshape(4, 5)
print(r2.shape)
r2

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
r3 = a.reshape(2, 2, -1)
print(r3.shape)
r3

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 차원 늘리기(확장)
- Dummy axis(축)을 늘린다
- reshape()을 이용해 늘릴 수 있다
- indexer와 np.newaxis 변수를 이용해 늘린다
    - ndarray[..., np.newaxis] 또는 ndarray[np.newaxis, ...]
        - 맨앞 또는 맨 마지막에 dummy axis(축)을 늘릴때 사용
        - 축을 늘리려는 위치에 np.newaxis를 지정하고 ... 으로 원본 배열의 shape을 유지함

In [53]:
print(a.shape)
r1 = np.reshape(20, 1)
r1 = a.reshape(-1, 1)
print(r1.shape)
r1 = a.reshape(1, -1)
print(r1.shape)

(20,)
(20, 1)
(1, 20)


In [55]:
# 다차원
print(a2.shape)
r2 = a2.reshape(1, 5, 2, -1)
print(r2.shape)
r2 = a2.reshape(5, 2, 3, 1)
print(r2.shape)

(5, 2, 3)
(1, 5, 2, 3)
(5, 2, 3, 1)


In [58]:
print(a.shape)
print(a[..., np.newaxis].shape)
print(a[np.newaxis, ...].shape)

(20,)
(20, 1)
(1, 20)


In [59]:
# 다차원
print(a2.shape)
print(a2[np.newaxis, ...].shape)
print(a2[..., np.newaxis].shape)

(5, 2, 3)
(1, 5, 2, 3)
(5, 2, 3, 1)


In [60]:
r = np.expand_dims(a2, axis = 2) # a2의 2번축에 dummy axis를 추가
print(r.shape)
r = np.expand_dims(a2, axis = 0) # a2의 0번축에 추가
print(r.shape)
r = np.expand_dims(a2, axis = -1) # a2의 마지막축에 추가
print(r.shape)

(5, 2, 1, 3)
(1, 5, 2, 3)
(5, 2, 3, 1)


### 차원 줄이기(축소)
#### numpy.squeeze(배열, axis = None), 배열객체, squeeze(axis = None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다
- 제거하려는 축의 size는 1이어야 한다
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3, 1, 1, 2) => (3, 2)
- squeeze는 한번에 하나씩만 제거 가능

In [61]:
a = np.arange(12).reshape(1, 2, 1, 2, 3, 1)
a.shape

(1, 2, 1, 2, 3, 1)

In [62]:
r1 = a.reshape(2, 2, 3)
r1.shape

(2, 2, 3)

In [63]:
r2 = a.squeeze() # reshape한 새로운 배열을 생성해서 반환
r2.shape

(2, 2, 3)

In [65]:
r3 = a.squeeze(axis = 2)
r3.shape

(1, 2, 2, 3, 1)

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다

In [67]:
print(a.shape)
print(a)
a.reshape(-1)

(1, 2, 1, 2, 3, 1)
[[[[[[ 0]
     [ 1]
     [ 2]]

    [[ 3]
     [ 4]
     [ 5]]]]



  [[[[ 6]
     [ 7]
     [ 8]]

    [[ 9]
     [10]
     [11]]]]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
r = a.flatten()
print(r.shape)
r

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
a = np.arange(15).reshape(3, 5)
a.shape

(3, 5)

In [70]:
r = a.T # (3, 5) -> (5, 3) 변환
r.shape

(5, 3)

In [72]:
a2 = np.arange(60).reshape(3, 4, 5)
a2.shape

(3, 4, 5)

In [74]:
r2 = np.transpose(a2, (2, 0, 1)) # 대상 배열, 축을 어떻게 이동
print(a2.shape)
r2.shape

(3, 4, 5)


(5, 3, 4)